### ISSUE TITLE
Nested middlewares

### ISSUE THREAD

**Issue by hoangnd25** [HealthEngineAU/popeye#1]
I think it is beneficial to be able to nest middlewares like this:

```
$layer1Middleware
    ->add(function ($appt, $next) {
    })
    ->add(function ($appt, $next) {
        // error handling here
    })

$layer2Middleware
    ->add(function ($appt, $next) {
    })
    ->add(function ($appt, $next) {
    })
    ->add(function ($appt, $next) {
        // error handling here
    })

$mainMiddleware
    ->add($layer1)
    ->add($layer2)
    ->add(function ($appt, $next) {
        // error handling here
    })
```

Reasons:
- Easy to add local error handling (exiting a layer without exiting the main middleware)
- Each layer can be reused

Implementation:
- I think just simple flatten each layer's queue and add it to main queue would work

**Comment by jradtilbrook** [comment]
This gave me another thought as well that would probably suit this and the project generally; adding the magic `__invoke()` method so a middleware is directly callable. Adding that would basically do what you propose
